language: csharp
mono: none
dotnet: 1.0.0-preview2-003131
sudo: false
os: linux
dist: trusty

cache:
  directories:
    - $HOME/.local/share/NuGet/Cache
    - tools

install:
  - dotnet restore

script:
  - cd test/WordPress.Test && dotnet test
